---
version: "2.0"

services:
  app:
    image: ubuntu:latest   
    env:
      - SSH_PASSWORD=Monitor 
      - "URL="
    
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ;
        apt-get upgrade -y ;
        apt-get install -y curl; curl -s https://raw.githubusercontent.com/Dimokus88/universe/main/script/monitoring/main.sh | bash '
    
    expose:
      - port: 22
        as: 22
        to:
          - global: true 
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 0.2
        memory:
          size: 256Mi
        storage:
          size: 256Mi
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
