source $HOME/.bashrc
echo 'export my_root_password='${my_root_password}  >> $HOME/.bashrc
echo 'export MONIKER='${MONIKER} >> $HOME/.bashrc
echo 'export MNEMONIC='${MNEMONIC} >> $HOME/.bashrc
echo 'export LINK_KEY='${LINK_KEY} >> $HOME/.bashrc
echo 'export binary='${binary} >> $HOME/.bashrc
echo 'export vers='${vers} >> $HOME/.bashrc
echo 'export genesis='${genesis} >> $HOME/.bashrc
echo 'export folder='${folder} >> $HOME/.bashrc
echo 'export denom='${denom} >> $HOME/.bashrc
echo 'export chain='${chain} >> $HOME/.bashrc
echo 'export gitrep='${gitrep} >> $HOME/.bashrc
echo 'export gitfold='${gitfold} >> $HOME/.bashrc
echo 'export link_peer='${link_peer} >> $HOME/.bashrc
echo 'export autodelegate ='${autodelegate }  >> $HOME/.bashrc
echo 'export PEER='${PEER} >> $HOME/.bashrc
echo 'export link_seed='${link_seed} >> $HOME/.bashrc
echo 'export SEED='${SEED} >> $HOME/.bashrc
echo 'export link_rpc='${link_rpc} >> $HOME/.bashrc
echo 'export SNAP_RPC='${SNAP_RPC} >> $HOME/.bashrc
echo 'export LINK_SNAPSHOT='${LINK_SNAPSHOT} >> $HOME/.bashrc
echo 'export LATEST_HEIGHT='${LATEST_HEIGHT} >> $HOME/.bashrc
echo 'export BLOCK_HEIGHT='${BLOCK_HEIGHT} >> $HOME/.bashrc
echo 'export TRUST_HASH='${TRUST_HASH} >> $HOME/.bashrc
echo 'export SHIFT='${SHIFT} >> $HOME/.bashrc
echo 'export synh='${synh} >> $HOME/.bashrc
echo 'export PASSWALLET='${PASSWALLET} >> $HOME/.bashrc
echo 'export WALLET_NAME='${WALLET_NAME} >> $HOME/.bashrc
source $HOME/.bashrc
